apiVersion: v1
kind: Secret
metadata:
  name: oauth-jwt-cookie-secret
  namespace: openfuyao-system
type: Opaque
data:
  oauth-jwt.key: |
    {{ .Values.config.oauthServerConfig.JWTPrivateKey }}
  oauth-cookie-sign.key: |
    {{ .Values.config.loginSessionConfig.signingKey }}
  oauth-cookie-encrypt.key: |
    {{ .Values.config.loginSessionConfig.encryptionKey }}
