apiVersion: v1
kind: Secret
metadata:
  name: oauth-client-secrets
  namespace: openfuyao-system
type: Opaque
data:
  client-mapper: {{ .Values.config.oauthServerConfig.clientIDSecret | b64enc | quote }}