apiVersion: v1
kind: Service
metadata:
  name: oauth-server
  namespace: openfuyao-system
spec:
  ports:
    - port: {{ .Values.config.httpServerConfig.port }}
      protocol: TCP
      targetPort: {{ .Values.config.httpServerConfig.port }}
      {{- if .Values.config.httpServerConfig.nodePort }}
      nodePort: {{ .Values.config.httpServerConfig.nodePort }}
      {{- end }}
  selector:
    application: "oauth-server"
  type: {{ if .Values.config.httpServerConfig.nodePort }}NodePort{{ else }}ClusterIP{{ end }}
